###########
# site.title

title:    'MinePilot'
subtitle: 'An End-to-End Automatic Obstacle Avoidance Agent'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-slate

mathjax: true